import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import localFont from "next/font/local";
import Navbar from "@/app/component/Navbar";

const eduFont = localFont({
    src:[
        {
            path:'./fonts/Regular.ttf',
            weight:'400',
            style:'normal',
        },
        {
            path:'./fonts/Medium.ttf',
            weight:'500',
            style:'normal',
        },
        {
            path:'./fonts/SemiBold.ttf',
            weight:'600',
            style:'normal',
        },
        {
            path:'./fonts/Bold.ttf',
            weight:'700',
            style:'normal',
        },
    ],
    variable:'--font-edufont',
    display:'swap'
})

export const metadata: Metadata = {
  title: "SunVogue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={eduFont.variable}>
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
